directories:
  output: "processed"

files:
  dataset: "dataset.jsonl"
  samples: "samples.jsonl"

preprocessing:
  min_context_window: 3
  max_context_window: 5
  short_response_word_count: 3
  short_response_downsample_rate: 0.60
  known_bots:
    - "clyde"
    - "freestuff"
    - "system"
  placeholders:
    - "[Attachment]"
    - "[Link]"
    - "[Empty/Reaction]"

sampling:
  target_total_samples: 100